import type { Link } from "@/types/link";

export const dummyLinks: Link[] = [
  {
    id: "dummy-1",
    user_id: "dummy-user",
    url: "https://nextjs.org/docs/app",
    title: "Next.js 16 App Router 공식 문서 정리",
    thumbnail_url: "https://picsum.photos/seed/1/400/225",
    description: "App Router의 라우팅, 레이아웃, 서버 컴포넌트를 다루는 공식 가이드",
    tags: ["Next.js", "React", "프론트엔드"],
    memo: "cacheComponents 옵션 도입 전에 다시 읽어보기",
    is_read: false,
    is_favorite: true,
    created_at: "2026-08-25T09:57:00.000Z",
  },
  {
    id: "dummy-2",
    user_id: "dummy-user",
    url: "https://supabase.com/docs/guides/database/postgres/row-level-security",
    title: "Supabase RLS 정책 설계 시 주의할 점 5가지",
    thumbnail_url: "https://picsum.photos/seed/2/400/225",
    description: "행 단위 보안 정책을 설계할 때 흔히 하는 실수 정리",
    tags: ["Supabase", "보안"],
    memo: null,
    is_read: true,
    is_favorite: false,
    created_at: "2026-08-25T07:30:00.000Z",
  },
  {
    id: "dummy-3",
    user_id: "dummy-user",
    url: "https://www.typescriptlang.org/docs/handbook/2/generics.html",
    title: "타입스크립트 제네릭 완전정복",
    thumbnail_url: null,
    description: "제네릭 함수, 제약 조건, 유틸리티 타입까지 다루는 핸드북",
    tags: ["TypeScript", "제네릭", "타입", "핸드북", "학습"],
    memo: "팀 스터디 자료로 활용",
    is_read: false,
    is_favorite: false,
    created_at: "2026-08-25T03:30:00.000Z",
  },
  {
    id: "dummy-4",
    user_id: "dummy-user",
    url: "https://example.com/articles/rsc-boundary",
    title:
      "React 서버 컴포넌트와 클라이언트 컴포넌트의 경계는 어디까지이며 실전 프로젝트에서 이를 어떻게 나누어야 하는가에 대한 아주 긴 제목 테스트용 아티클",
    thumbnail_url: "https://picsum.photos/seed/4/400/225",
    description: null,
    tags: ["React"],
    memo: null,
    is_read: true,
    is_favorite: true,
    created_at: "2026-08-24T10:00:00.000Z",
  },
  {
    id: "dummy-5",
    user_id: "dummy-user",
    url: "https://tailwindcss.com/docs/upgrade-guide",
    title: "Tailwind CSS v4 마이그레이션 가이드",
    thumbnail_url: null,
    description: null,
    tags: [],
    memo: null,
    is_read: false,
    is_favorite: false,
    created_at: "2026-08-22T10:00:00.000Z",
  },
  {
    id: "dummy-6",
    user_id: "dummy-user",
    url: "https://example.com/articles/2024/how-to-build-scalable-web-applications-with-nextjs?utm_source=newsletter&utm_medium=email&utm_campaign=summer2024&ref=homepage&session_id=abcdef1234567890",
    title: "이 링크는 아주 길고 지저분한 쿼리스트링과 트래킹 파라미터가 잔뜩 붙은 URL 테스트용 게시물",
    thumbnail_url: "https://picsum.photos/seed/6/400/225",
    description: "URL 표시 시 도메인만 추출해서 보여주는지 확인하는 케이스",
    tags: ["테스트", "URL", "엣지케이스", "표시"],
    memo: null,
    is_read: true,
    is_favorite: false,
    created_at: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "dummy-7",
    user_id: "dummy-user",
    url: "https://github.com/features/actions",
    title: "GitHub Actions로 CI/CD 파이프라인 구축하기",
    thumbnail_url: "https://picsum.photos/seed/7/400/225",
    description: null,
    tags: ["CI/CD", "GitHub"],
    memo: "배포 자동화할 때 참고",
    is_read: false,
    is_favorite: true,
    created_at: "2026-08-11T10:00:00.000Z",
  },
  {
    id: "dummy-8",
    user_id: "dummy-user",
    url: "https://example.com/blog/design-system-retrospective",
    title: "디자인 시스템 구축 회고",
    thumbnail_url: null,
    description: "1년간 디자인 시스템을 운영하며 배운 것들",
    tags: ["디자인시스템"],
    memo: null,
    is_read: true,
    is_favorite: true,
    created_at: "2026-07-25T10:00:00.000Z",
  },
  {
    id: "dummy-9",
    user_id: "dummy-user",
    url: "https://example.com/study/algorithm-week6",
    title: "알고리즘 스터디 6주차 정리",
    thumbnail_url: "https://picsum.photos/seed/9/400/225",
    description: "그래프 탐색(BFS/DFS) 문제 풀이 모음",
    tags: [],
    memo: "다음 주차 전에 복습",
    is_read: false,
    is_favorite: false,
    created_at: "2026-05-25T10:00:00.000Z",
  },
  {
    id: "dummy-10",
    user_id: "dummy-user",
    url: "https://example.com/old-bookmark",
    title: "북마크 정리 안 한 지 오래된 글",
    thumbnail_url: null,
    description: null,
    tags: [],
    memo: null,
    is_read: true,
    is_favorite: false,
    created_at: "2025-08-25T10:00:00.000Z",
  },
];
